language: php
php:
  - 5.4
  - 5.5

env:
  - DB=mysql

install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

script: phpunit tests/

notifications:
  webhooks:
    - https://idobata.io/hook/ac04f31c-3983-4637-b486-ea9d442f7e91
  on_success: change # default: always
  on_failure: always # default: always [always|never|change]
  on_start: false # default: false [true|false]