CREATE USER 'blogapp'@'localhost' IDENTIFIED BY 'foobar';
GRANT USAGE ON *.* TO 'blogapp'@'localhost';
GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE,
 CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT,
  REFERENCES, TRIGGER, UPDATE, LOCK TABLES
  ON `blogapp`.* TO 'blogapp'@'localhost' WITH GRANT OPTION;
GRANT SUPER  ON *.* TO 'blogapp'@'localhost';
FLUSH PRIVILEGES;